// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HiEFk8SMDqVAeuvgQWYtI-ZqqptMAno',
    appId: '1:79383593534:web:7305b5218648d14c6a876f',
    messagingSenderId: '79383593534',
    projectId: 'aahar-d30b3',
    authDomain: 'aahar-d30b3.firebaseapp.com',
    storageBucket: 'aahar-d30b3.firebasestorage.app',
    measurementId: 'G-MG6H1V1NB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aeVHGVdnsJgfCg4ZqgrTUTgCHYaLV68',
    appId: '1:79383593534:android:a0b11c076a2068576a876f',
    messagingSenderId: '79383593534',
    projectId: 'aahar-d30b3',
    storageBucket: 'aahar-d30b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEh8o43pRbSEFHUtx6Brj8UPOOhdO_Zug',
    appId: '1:79383593534:ios:f392102ecf720af86a876f',
    messagingSenderId: '79383593534',
    projectId: 'aahar-d30b3',
    storageBucket: 'aahar-d30b3.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );
}
